### ISSUE TITLE
Si è persa la modifica del limite dell'upload dei file.

### ISSUE THREAD

**Issue by CodiceMatrix** [NemesiX/odoo#1]
Ciao @rpiva ,
mi ha chiamato cashpos che non riesce ad aggiornare le casse di Villasport.
L'errore è quello famoso del limite dei 25Mega.

![Schermata 2022-01-28 alle 15 06 27](https://user-images.githubusercontent.com/63808967/151569186-5a48b780-77c8-4b13-9a86-acea7cb79adf.png)

Sicuramente ci siamo persi questa cosa .

Ti lascio il memo che mi ero scritto a suo tempo.

https://sites.google.com/a/nemesix.it/wiki/documentazione/openerp/odoo-superare-il-limite-di-upload-attualmente-impostato-a-25mb

Spero non ci siano altre cose del genere in giro nel codice.

**Comment by CodiceMatrix** [comment]
I 3 clienti CashPos con il problema sono 
bema.nempos.*
villasport.nempos.*
spremulli.nempos.*

**Comment by rpiva** [comment]
Problema risolto

Saluti,
Roberto



Il giorno ven 28 gen 2022 alle ore 16:02 Zizzo ***@***.***>
ha scritto:

**Comment by CodiceMatrix** [comment]
![g2Mb](https://user-images.githubusercontent.com/63808967/151592123-55abe026-6e43-4812-a108-90fb55fd1eb2.gif)
