### ISSUE TITLE
Nnuova versione di Odoo da repository: Errore nel form sequenze.

### ISSUE THREAD

**Issue by CodiceMatrix** [NemesiX/odoo#3]
Ciao @giorgioborri ,
in produzione stiamo usando questo progetto odoo https://github.com/NemesiX/odoo/tree/7.0 quindi occorre che ti allenai anche tu.

ti ho inviato un file tramite wetransfer per facilitare le verifiche del caso.

All'interno del file hai la cartella odoo "VECCHIA" e "NUOVA" ovveo quella che si scarica da questo repository.

![Schermata 2022-02-15 alle 15 18 51](https://user-images.githubusercontent.com/63808967/154082798-81e21861-fa57-4347-ab6e-a56a9221f491.png)

Come puoi vedere mi sono fatto un LINK in modo da passare velocemente da una versione ad un altra.
Ultimamente @rpiva ha fatto delle modifiche alla versione base di odoo per permettere alle nostre App sviluppate in flutter di collegarsi a odoo.

A parte questo il problema che vorrei che tu controllassi è quello che compare quando tento di entrare nel menù delle sequenze .

![Schermata 2022-02-15 alle 15 37 16](https://user-images.githubusercontent.com/63808967/154083868-3d1601cd-02de-4625-b306-26c9ca1e42e5.png)

Questo screenshot è preso da demo.nempos.com

**Comment by CodiceMatrix** [comment]
Questo è il link WeTransfer per scaricare direttamente la cartella odoo che c'è in laboratorio contenente la nuova versione e la vecchia del ramo 7.0 --> https://we.tl/t-iPByFg731N

**Comment by giorgioborri** [comment]
mi dici : modificato odoo per permettere alle nostre App sviluppate in
flutter di collegarsi a odoo.

per il collegamento dall'esterno era sufficiente la libreria jsonrpc in
dart. perché avete dovuto modificare odoo?

Il giorno mar 15 feb 2022 alle ore 15:38 Zizzo ***@***.***>
ha scritto:

**Comment by CodiceMatrix** [comment]
Scusa , le WEB APP sviluppate in flutter! Le app già funzionavano anzi funzionano.
Con la parte WEB ci sono dei limiti che ha aggirato @rpiva con le modifiche che ha fatto sul ramo ufficiale ma a parte questo avevamo già fatto un ramo della 7 e dovevamo usare quello perchè odoo 7 non è più manutenuto quindi è giusto farsi un ramo e continuare noi su quello. Però sembra esserci un problema sul ramo ufficiale.

**Comment by giorgioborri** [comment]
Per le sequenze era stata fatta qualche correzione perchè la gestione automatica dei progressivi fornita da postgres era cambiata passando dal 9.5 a 9.6 o a 10 (sicuramente nella versione 10 era cambiato) per cui era stato aggiornata la libreria base. se provate a confrontare questa nei 2 progetti new e old e a rimettere in new la modifica dovrebbe essere ciò che basta a far funzionare il sistema

**Comment by giorgioborri** [comment]
la libreria jsonrpc in dart dava problemi con odoo 7?

Il giorno mar 15 feb 2022 alle ore 16:12 Zizzo ***@***.***>
ha scritto:

**Comment by giorgioborri** [comment]
ritornando alla sequenza: controllate i file  7.0/openerp/addons/base/ir/ir_sequence.py

**Comment by rpiva** [comment]
Sono stato costretto a fare delle modifiche per configurare il CORS
necessario per far funzionare NemPOS Delivery V2 sottoforma di web app,
altrimenti essendo NemPOS Delivery pubblicato sotto un altro dominio
rispetto a NemPOS Backoffice il browser non gli faceva accedere a XMLRPC e
JSONRPC.

Saluti,
Roberto



Il giorno mar 15 feb 2022 alle ore 16:21 giorgioborri <
***@***.***> ha scritto:

**Comment by rpiva** [comment]
Dal momento che Odoo 7.0 non è più manutenuto ho fatto un fork ed ho già
fatto delle modifiche direttamente al codice "base" perchè non mi è parso
che fosse possibile modificare tramite modulo la base di XMLRPC e JSONRPC

Saluti,
Roberto



Il giorno mar 15 feb 2022 alle ore 16:23 giorgioborri <
***@***.***> ha scritto:

**Comment by CodiceMatrix** [comment]
Ciao @giorgioborri ,
ho visto che le differenze sono in questi file:
```
root@Odoo-Lab-Lenovo:/opt/odoo# diff -r --brief --exclude=*.pyc 7.0.NEW 7.0.OLD
I file 7.0.NEW/addons/web/http.py e 7.0.OLD/addons/web/http.py sono diversi
I file 7.0.NEW/addons/web/static/src/js/pyeval.js e 7.0.OLD/addons/web/static/src/js/pyeval.js sono diversi
Solo in 7.0.OLD/addons/web/static/src/js: pyeval.js.ori
I file 7.0.NEW/addons/web/static/src/js/view_form.js e 7.0.OLD/addons/web/static/src/js/view_form.js sono diversi
Solo in 7.0.NEW: .git
I file 7.0.NEW/openerp/addons/base/ir/ir_sequence.py e 7.0.OLD/openerp/addons/base/ir/ir_sequence.py sono diversi
I file 7.0.NEW/openerp/service/wsgi_server.py e 7.0.OLD/openerp/service/wsgi_server.py sono diversi
```

**Comment by rpiva** [comment]
Io ho modificato solo http.py e wsgi_server.py gli altri non so cosa siano

Ci sarebbe da andare più nel dettaglio del ir_sequence.py per capire cosa
ci sia di diverso e valutare se portare la versione "old" nel repo nuovo.
Stessa cosa vale per i js


Saluti,
Roberto



Il giorno mar 15 feb 2022 alle ore 16:32 Zizzo ***@***.***>
ha scritto:

**Comment by giorgioborri** [comment]
ho visto i commit che avete fatto: nei file js ci sono correzioni per la
dimensione del upload ammesso ora fino a 100mb

il file ir_sequence in old invece contenere le correzioni  aggiunte per
gestire i seriali nel nuovo modo di postgres 9.6 o 10 sicuramente

Il giorno mar 15 feb 2022 alle ore 16:44 Roberto :-p <
***@***.***> ha scritto:

**Comment by CodiceMatrix** [comment]
Ciao @rpiva ,
ho trovato questa vecchia mail.
Ti ricorda qualcosa?
Perchè a questo punto basta rimettere il file ir_sequence.py precedente che è comunque quello più aggiornato.

![Schermata 2022-02-15 alle 17 58 30](https://user-images.githubusercontent.com/63808967/154110921-ed50f1af-7fa1-4920-bf9c-40aa911a75ce.png)
 
In allegato alla tua mail del 18 dic 2018 alle 15:54 il file era questo :

[ir_sequence.py.zip](https://github.com/NemesiX/odoo/files/8073045/ir_sequence.py.zip)

**Comment by rpiva** [comment]
Azz
Allora ci sono da tenere buoni i file .js e ir_sequence.py della versione
vecchia. poi push e via di nuova immagine.


Saluti,
Roberto



Il giorno mar 15 feb 2022 alle ore 18:01 Zizzo ***@***.***>
ha scritto:

**Comment by CodiceMatrix** [comment]
Preso file ir_sequence.py della versione vecchia e fatto commit e push.

**Comment by giorgioborri** [comment]
hai trovato le differenze nei file

I file 7.0.NEW/addons/web/static/src/js/pyeval.js e
7.0.OLD/addons/web/static/src/js/pyeval.js sono diversi

Questo file in particolare era stato corretto per permettere di
semplificare i calcoli di date in nx_hr -> interfaccia turni  ed anche
in alcuni filtri search

si dovrebbe copiare la versioni in old e mettere in new



Il giorno mar 15 feb 2022 alle ore 16:32 Zizzo ***@***.***>
ha scritto:

**Comment by CodiceMatrix** [comment]
Si perfetto.
Abbiamo già preso il vecchio file ir_sequence.py e messo i questo repository che è poi quello che viene scaricato durante la creazione di un Docker. ( c'è un mio commit )
Bisogna che in sviluppo cominciamo ad usare questo repository , c'è solo un problema che dobbiamo risolvere quando si usa http invece di https ma risolto quello poi dobbiamo usarlo in sviluppo.

**Comment by giorgioborri** [comment]
ti ho indicato un altro file: pyeval.js
anche questo va considerato dal old a new
pensavo che lo controllassi ieri dato che ti è risultato con la ricerca di
differenze

Il giorno mer 16 feb 2022 alle ore 11:26 Zizzo ***@***.***>
ha scritto:

**Comment by CodiceMatrix** [comment]
Ciao @giorgioborri ,
non l'ho fatto perchè ero convinto che fosse per il file della dimensione del Upload ma non è così.
Queste sono le differenze qualcuno si ricorda perchè è stata fatta questa modifica?

![Schermata 2022-02-16 alle 12 24 30](https://user-images.githubusercontent.com/63808967/154255275-74add077-fa65-45e0-b88a-38ae80606d7f.png)

**Comment by giorgioborri** [comment]
ti avevo già indicato nella prima mail cosa era stato fatto: sono stati
aggiunti dei parametri in alcune funzioni da essere usate nel modulo
nx_hr interfaccia turni


Il giorno mer 16 feb 2022 alle ore 12:26 Zizzo ***@***.***>
ha scritto:

**Comment by CodiceMatrix** [comment]
OK @giorgioborri ,
ho creato il commit f974dd675087201c5455f7a8e61f17a721dc5d13 che contiene il file pyeval.js corretto per HR.

**Comment by CodiceMatrix** [comment]
@rpiva alla prossima immagine docker ricordati che c'è anche da pullare la cartella odoo.

**Comment by rpiva** [comment]
Meglio che tu lo faccia direttamente piuttosto che ci dimentichiamo

**Comment by CodiceMatrix** [comment]
Ho fatto la cartella 7.0. Quali altre cartelle devo fare?

![Schermata 2022-02-18 alle 18 51 45](https://user-images.githubusercontent.com/63808967/154736005-56db941e-5397-4132-88e6-487c822b11fc.png)
